// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using backend.Database;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(Postgres_Context))]
    [Migration("20260909074223_othertables2")]
    partial class othertables2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MusiciansSongs", b =>
                {
                    b.Property<Guid>("other_singersmusician_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("songssong_id")
                        .HasColumnType("uuid");

                    b.HasKey("other_singersmusician_id", "songssong_id");

                    b.HasIndex("songssong_id");

                    b.ToTable("MusiciansSongs");
                });

            modelBuilder.Entity("backend.Database.Albums", b =>
                {
                    b.Property<Guid>("album_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("Musiciansmusician_id")
                        .HasColumnType("uuid");

                    b.Property<string>("album_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("likes")
                        .HasColumnType("integer");

                    b.HasKey("album_id");

                    b.HasIndex("Musiciansmusician_id");

                    b.ToTable("AlbumsTable");
                });

            modelBuilder.Entity("backend.Database.Musicians", b =>
                {
                    b.Property<Guid>("musician_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("musician_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("musician_id");

                    b.ToTable("Musicians");
                });

            modelBuilder.Entity("backend.Database.Songs", b =>
                {
                    b.Property<Guid>("song_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("Albumsalbum_id")
                        .HasColumnType("uuid");

                    b.Property<int>("likes")
                        .HasColumnType("integer");

                    b.Property<string>("song_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("song_id");

                    b.HasIndex("Albumsalbum_id");

                    b.ToTable("SongsTable");
                });

            modelBuilder.Entity("backend.Database.User", b =>
                {
                    b.Property<Guid>("user_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("musician_id")
                        .HasColumnType("uuid");

                    b.Property<string>("user_mail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("user_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("user_pass")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("user_id");

                    b.ToTable("UsersTable");
                });

            modelBuilder.Entity("MusiciansSongs", b =>
                {
                    b.HasOne("backend.Database.Musicians", null)
                        .WithMany()
                        .HasForeignKey("other_singersmusician_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Database.Songs", null)
                        .WithMany()
                        .HasForeignKey("songssong_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("backend.Database.Albums", b =>
                {
                    b.HasOne("backend.Database.Musicians", null)
                        .WithMany("albums")
                        .HasForeignKey("Musiciansmusician_id");
                });

            modelBuilder.Entity("backend.Database.Songs", b =>
                {
                    b.HasOne("backend.Database.Albums", null)
                        .WithMany("songs")
                        .HasForeignKey("Albumsalbum_id");
                });

            modelBuilder.Entity("backend.Database.Albums", b =>
                {
                    b.Navigation("songs");
                });

            modelBuilder.Entity("backend.Database.Musicians", b =>
                {
                    b.Navigation("albums");
                });
#pragma warning restore 612, 618
        }
    }
}
