// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using backend.Database;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(Postgres_Context))]
    [Migration("20260917165325_Initialasdddddddddddddddddd")]
    partial class Initialasdddddddddddddddddd
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("backend.Database.Albums", b =>
                {
                    b.Property<Guid>("album_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("album_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("likes")
                        .HasColumnType("integer");

                    b.Property<Guid>("musician_id")
                        .HasColumnType("uuid");

                    b.Property<List<Guid>>("songs")
                        .IsRequired()
                        .HasColumnType("uuid[]");

                    b.Property<string>("visibility")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("album_id");

                    b.ToTable("AlbumsTable");
                });

            modelBuilder.Entity("backend.Database.Musicians", b =>
                {
                    b.Property<Guid>("musician_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<List<Guid>>("albums")
                        .IsRequired()
                        .HasColumnType("uuid[]");

                    b.Property<string>("musician_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<List<Guid>>("songs")
                        .IsRequired()
                        .HasColumnType("uuid[]");

                    b.Property<Guid>("user_id")
                        .HasColumnType("uuid");

                    b.HasKey("musician_id");

                    b.ToTable("MusiciansTable");
                });

            modelBuilder.Entity("backend.Database.Playlists", b =>
                {
                    b.Property<Guid>("playlist_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<List<Guid>>("songs")
                        .IsRequired()
                        .HasColumnType("uuid[]");

                    b.Property<Guid>("user_id")
                        .HasColumnType("uuid");

                    b.HasKey("playlist_id");

                    b.ToTable("PlaylistsTable");
                });

            modelBuilder.Entity("backend.Database.Songs", b =>
                {
                    b.Property<Guid>("song_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("file_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("likes")
                        .HasColumnType("integer");

                    b.Property<Guid>("musician_id")
                        .HasColumnType("uuid");

                    b.Property<List<Guid>>("other_singers")
                        .IsRequired()
                        .HasColumnType("uuid[]");

                    b.Property<string>("song_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("visibility")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("song_id");

                    b.ToTable("SongsTable");
                });

            modelBuilder.Entity("backend.Database.User", b =>
                {
                    b.Property<Guid>("user_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<List<Guid>>("liked_albums")
                        .IsRequired()
                        .HasColumnType("uuid[]");

                    b.Property<List<Guid>>("liked_songs")
                        .IsRequired()
                        .HasColumnType("uuid[]");

                    b.Property<Guid?>("musician_id")
                        .HasColumnType("uuid");

                    b.Property<List<Guid>>("playlists")
                        .IsRequired()
                        .HasColumnType("uuid[]");

                    b.Property<string>("user_mail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("user_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("user_pass")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("user_id");

                    b.ToTable("UsersTable");
                });
#pragma warning restore 612, 618
        }
    }
}
